name: Norminette Check

on:
  push:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install norminette
        run: | 
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette

      - name: Run norminette
        run: norminette -R CheckForbiddenSourceheader
